server:
  port: 8082
spring:
  cloud:
    gateway:
      mvc:
        routes:
        - id: users-status-check
          uri: http://localhost:8081
          predicates:
            - Path=/users/status/check
            - Method=GET
          filters:
            - RemoveRequestHeader=Cookie
        - id: albums
          uri: http://localhost:8060
          predicates:
            - Path=/albums
            - Method=GET
          filters:
            - RemoveRequestHeader=Cookie
        - id: photos
          uri: http://localhost:8070
          predicates:
            - Path=/photos
            - Method=GET
          filters:
            - RemoveRequestHeader=Cookie