server:
  port: 8081
spring:
  application:
    name: resource-server
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8443/realms/appsdeveloperblog/protocol/openid-connect/certs
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka
